### ISSUE TITLE
Benchmark Info

### ISSUE THREAD

**Issue by daniel-corbett** [zevenet/zproxy#1]
Hello,

Can you please provide the software versions and configurations used for the benchmarks, as well as the appropriate configurations for the benchmark tool?

Thanks

**Comment by emiliocampos-zevenet** [comment]
Hi @dcorbett-haproxy, requested information below, if you have some Haproxy config recommendations please let us know and we will be glad to try it:

Haproxy version 1.8.19-1 (available in Debian Buster) and configuration file:
--------------------------
global
log /dev/log	local0
log /dev/log	local1 notice
chroot /var/lib/haproxy
stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
stats timeout 30s
user haproxy
group haproxy
daemon
nbproc	8
# Default SSL material locations
ca-base /etc/ssl/certs
crt-base /etc/ssl/private
#maxconn 1000000
# Default ciphers to use on SSL-enabled listening sockets.
# For more information, see ciphers(1SSL). This list is from:
#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
# An alternative list with additional directives can be obtained from
#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy

defaults
log	global
mode	http
option	httplog
option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
errorfile 400 /etc/haproxy/errors/400.http
errorfile 403 /etc/haproxy/errors/403.http
errorfile 408 /etc/haproxy/errors/408.http
errorfile 500 /etc/haproxy/errors/500.http
errorfile 502 /etc/haproxy/errors/502.http
errorfile 503 /etc/haproxy/errors/503.http
errorfile 504 /etc/haproxy/errors/504.http
frontend Local_Server
    bind 172.16.1.1:83
    mode	http

      default_backend My_Web_Servers

backend My_Web_Servers
    balance roundrobin
    option forwardfor
    server web1.example.com  172.16.0.12:80
    server web2.example.com  172.16.1.13:80
---------------------------------------

Client used: wrk (source code: https://github.com/wg/wrk)
command:
./wrk -d 15 -t 10 -c 400 http://172.16.1.1:80/hello.html

Backend servers used
nginx v. 1.10.3-1+deb9u3 replies a simple HTML of 42 bytes of content length


Used hardware in server: Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 cores)
Used hardware in client: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (8 cores)
Used hardware in backend: Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 cores)
Used kernel for the entire environment: Linux 4.9.110

**Comment by emiliocampos-zevenet** [comment]
We have created a dedicated directory with extended information, please refer to https://github.com/zevenet/zproxy/tree/master/benchmark 

I hope this help and thanks for your interest in zproxy.

**Comment by dcorbett-haproxy** [comment]
Excellent!  Thank you for the quick response.

**Comment by bedis** [comment]
I would recommend trying HAProxy 2.0 since this is the latest LTS release and try nbthread. In 2.0, you can also enable connection pooling.

If you want to stick to nbproc on 1.8, you must adjust the binds too:
`
bind 172.16.1.1:83 process 1
bind 172.16.1.1:83 process 2
bind 172.16.1.1:83 process 3
...
bind 172.16.1.1:83 process 8
`
And also do some cpu-map in your global section to ensure each HAProxy process run on its own cpu core.

NOTE: the tips above for 1.8 don't need to be applied to 2.0, they are now made automatically.


As a general manner, I would say 15s of load test is pretty short, I usually run for 1 to 5 minutes.

**Comment by emiliocampos-zevenet** [comment]
Hi @bedis thanks for your comments, Haproxy automatic process binding is a great feature, also developed in zproxy.

Following some benchmark, I have tested in lab Haproxy 2.0.8 as recommended. here some of the results:

Command execution against Haproxy (HA-Proxy version 2.0.8 2019/10/23 - https://haproxy.org/)
./wrk -d 15 -t 10 -c 400 http://172.16.1.1:83/hello.html

Result:
Running 15s test @ http://172.16.1.1:83/hello.html
  10 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.95ms   43.67ms   1.04s    96.82%
    Req/Sec    22.37k     3.96k   34.52k    74.32%
  3355232 requests in 15.10s, 812.75MB read
Requests/sec: 222207.03
Transfer/sec:     53.83MB

Command execution against zproxy 0.1.2 
./wrk -d 15 -t 10 -c 400 http://172.16.1.1:83/hello.html

Result:
Running 15s test @ http://172.16.1.1/hello.html
  10 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.89ms   75.98ms   1.22s    96.13%
    Req/Sec    24.68k     5.20k   45.16k    76.87%
  3684463 requests in 15.10s, 0.95GB read
Requests/sec: 244011.65
Transfer/sec:     64.68MB

Requests/sec seem to be more similar than in previous tested Haproxy version 1.8.19-1, congrats to the great work. 

I think that it could be great to do tests increasing time to 1-5mins as recommended and upgrade to NICs 10Gb, also compare CPU usage could be a good point. 

Anyway, thanks for your follow up in this matter.

**Comment by bedis** [comment]
Cool thanks for the quick feedback and being opened to update.
Can you enable "http-reuse always" to see what happens?

Can you confirm whether zproxy fully parses HTTP protocol on both the request and the response for all the traffic passing through, like HAProxy does?

**Comment by emiliocampos-zevenet** [comment]
Hi @bedis, I have executed a few more test with the directive "http-reuse always ", I don't see any change in the results after all, see below:

Command execution in client:
./wrk -d 15 -t 10 -c 400 http://172.16.1.1:83/hello.html

TEST1:
Running 15s test @ http://172.16.1.1:83/hello.html
  10 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.08ms  102.33ms   1.15s    96.50%
    Req/Sec    21.92k     3.79k   43.42k    91.36%
  3280414 requests in 15.10s, 794.63MB read
Requests/sec: 217263.02
Transfer/sec:     52.63MB

TEST2:
Running 15s test @ http://172.16.1.1:83/hello.html
  10 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.50ms   17.27ms 216.05ms   97.63%
    Req/Sec    22.51k     2.04k   42.82k    78.91%
  3376631 requests in 15.10s, 817.93MB read
Requests/sec: 223629.51
Transfer/sec:     54.17MB

TEST3:
Running 15s test @ http://172.16.1.1:83/hello.html
  10 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.86ms  104.50ms   1.04s    96.33%
    Req/Sec    21.94k     3.13k   34.45k    93.16%
  3287268 requests in 15.10s, 796.29MB read
Requests/sec: 217708.36
Transfer/sec:     52.74MB

In regards to the zproxy fully parses question, I can confirm that it manages request and response headers as HAproxy does.
