### ISSUE TITLE
Error downloading a 1M file or bigger

### ISSUE THREAD

**Issue by System25** [zevenet/zproxy#9]
Hi, I'm using Zevenet as a load balancer to balance the load of two Apache servers.
If I create a 1M file (for example):
  `head -c 1MB /dev/urandom > random.bin`

And then I download the file by using Zevenet as a HTTP load balancer, the file downloaded is not correct. If your compare the MD5 sum with the original you can see that there are differences:

```
$ md5sum random.bin*
35ace1a158f093621454aee30fa5bcc2  random.bin
d89e712b0c2e2cb994d192d97ff24d13  random.bin.1
```

My Zevenet version is:

  Zevenet Version: 5.11.0
  Appliance Version: ZCE 6
  Kernel Version: 4.19.0-6-amd64

And you can see that the balancing in the port 80 is made by zproxy.

```
# netstat -n -l -p
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.235.83.200:80        0.0.0.0:*               LISTEN      90222/zproxy        
tcp        0      0 10.235.83.200:80        0.0.0.0:*               LISTEN      90222/zproxy        
tcp        0      0 10.235.83.200:80        0.0.0.0:*               LISTEN      90222/zproxy        
tcp        0      0 10.235.83.200:80        0.0.0.0:*               LISTEN      90222/zproxy        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      402/sshd            
tcp        0      0 127.0.0.1:27            0.0.0.0:*               LISTEN      146281/nftlb        
tcp        0      0 0.0.0.0:444             0.0.0.0:*               LISTEN      414/cherokee-worker 
tcp6       0      0 :::22                   :::*                    LISTEN      402/sshd  
```

Thanks

**Comment by cano-devel** [comment]
Hello
Could you update and confirm the issue in the last version? 
Regards

**Comment by System25** [comment]
Hi, since that problem is happening in a production server I've tried to install the same version in a development server and tried to reproduce the same error. But I couldn't reproduce the error.

Sice I was playing with lx4nat and HTTP profile cofigurations, maybe something is not right in the kernel. So I will reboot the production server in a moment when no users are using the system and I'll let you know if that solves it.

Thanks

**Comment by System25** [comment]
Hi, after rebooting the server everything works fine.

Thanks

**Comment by System25** [comment]
Hi, after a couple of days this error came back again. I've tried rebooting the load balancer that the problem persist.
Now this problem happens with text files like por excample javascript files.

Attach you will see three files (the correct one and two wrong ones) so you can see the difference. You will see missing fragments of code and other fragments that are in the wrong order.

[prototype.js.error2.txt](https://github.com/zevenet/zproxy/files/7259919/prototype.js.error2.txt)
[prototype.js.error.txt](https://github.com/zevenet/zproxy/files/7259914/prototype.js.error.txt)
[prototype.js.txt](https://github.com/zevenet/zproxy/files/7259922/prototype.js.txt)

Thanks
